runtime: python37 # or another supported version

instance_class: B2

basic_scaling:
  max_instances: 4
  idle_timeout: 10m

entrypoint: uwsgi --http-socket :8080 --wsgi-file wsgi.py --callable app --master --processes 1 --threads 2

handlers:
  - url: /.*
    secure: optional
    script: auto
