# This is a workflow to download loading page files from webflow.com using selenium

name: CI for MCD backend

# Controls when the workflow will run
on:
  push:
    branches:
      - 'testing'
      - 'staging'
      - 'main'
  pull_request:
    branches:
      - 'testing'
      - 'staging'
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r  requirements.txt

      - name: Run tests and get coverage
        run: |
          pytest -v --cov=src
          coverage html

      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v2
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     directory: ./htmlcov
      #     fail_ci_if_error: true
      #     flags: unittests
      #     name: Coverage report
      #     verbose: true
